all_tables ={'EA': {'name': 'ddl_usr'},
 'EB': {'name': 'ddl_usr',
        'table_name': {'column_name': {'len': 'length',
                                       'sno': 1,
                                       'type': 'type'}},
        'tbl_a': {'col_a_1': {'len': 5, 'sno': 1, 'type': 'char'},
                  'col_a_10': {'len': 6, 'sno': 10, 'type': 'char'},
                  'col_a_2': {'len': 6, 'sno': 2, 'type': 'char'},
                  'col_a_3': {'len': 7, 'sno': 3, 'type': 'char'},
                  'col_a_4': {'len': 8, 'sno': 4, 'type': 'char'},
                  'col_a_5': {'len': 1, 'sno': 5, 'type': 'number'},
                  'col_a_6': {'len': 2, 'sno': 6, 'type': 'char'},
                  'col_a_7': {'len': 3, 'sno': 7, 'type': 'char'},
                  'col_a_8': {'len': 3, 'sno': 8, 'type': 'char'},
                  'col_a_9': {'len': 5, 'sno': 9, 'type': 'char'}},
        'tbl_b': {'col_b_1': {'len': 7, 'sno': 1, 'type': 'char'},
                  'col_b_4': {'len': 10, 'sno': 2, 'type': 'char'},
                  'col_b_5': {'len': 3, 'sno': 3, 'type': 'char'}},
        'tbl_c': {'col_c_1': {'len': 4, 'sno': 1, 'type': 'char'},
                  'col_c_2': {'len': 5, 'sno': 2, 'type': 'number'},
                  'col_c_3': {'len': 6, 'sno': 3, 'type': 'number'},
                  'col_c_4': {'len': 7, 'sno': 4, 'type': 'number'},
                  'col_c_5': {'len': 8, 'sno': 5, 'type': 'number'},
                  'col_c_6': {'len': 9, 'sno': 6, 'type': 'number'}},
        'tbl_d': {'col_d_1': {'len': 1, 'sno': 1, 'type': 'number'},
                  'col_d_2': {'len': 2, 'sno': 2, 'type': 'number'},
                  'col_d_3': {'len': 3, 'sno': 3, 'type': 'number'},
                  'col_d_4': {'len': 4, 'sno': 4, 'type': 'char'}}},
 'EE': {'name': 'ddl_usr'},
 'EK': {'name': 'ddl_usr'}}