all_datas ={'EA': {'name': 'dml_usr',
        'str': {1: {}, 'sno': 1},
        'tbl_a': {1: {'col_a_1': '124',
                      'col_a_2': 'EB',
                      'col_a_3': '1',
                      'col_a_4': 'aa'},
                  2: {'col_a_1': '124',
                      'col_a_2': 'EB',
                      'col_a_3': '2',
                      'col_a_4': 'aa'},
                  3: {'col_a_1': '124',
                      'col_a_2': 'EB',
                      'col_a_3': '3',
                      'col_a_4': 'bb'},
                  'sno': 3},
        'tbl_b': {1: {'col_b_1': '124',
                      'col_b_2': 'EB',
                      'col_b_3': '1',
                      'col_b_4': 'aa'},
                  2: {'col_b_1': '124',
                      'col_b_2': 'EB',
                      'col_b_3': '1',
                      'col_b_4': 'aa'},
                  3: {'col_b_1': '124',
                      'col_b_2': 'EB',
                      'col_b_3': '3',
                      'col_b_4': 'aa',
                      'col_b_5': 'ee'},
                  'sno': 3}},
 'EB': {'name': 'dml_usr'},
 'EE': {'name': 'dml_usr'},
 'EK': {'name': 'dml_usr'}}