all_datas ={'EA': {'name': 'dml_pkg',
        'str': {1: {}, 'sno': 1},
        'tbl_a': {1: {'col_a_1': '124',
                      'col_a_2': 'EB',
                      'col_a_3': '1',
                      'col_a_4': 'aa'},
                  2: {'col_a_1': '124',
                      'col_a_2': 'EB',
                      'col_a_3': '2',
                      'col_a_4': 'aa'},
                  3: {'col_a_1': '124',
                      'col_a_2': 'EB',
                      'col_a_3': '3',
                      'col_a_4': 'aa'},
                  'sno': 3},
        'tbl_b': {1: {'col_b_1': '124',
                      'col_b_2': 'EB',
                      'col_b_3': '1',
                      'col_b_4': 'aa'},
                  2: {'col_b_1': '124',
                      'col_b_2': 'EB',
                      'col_b_3': '1',
                      'col_b_4': 'aa'},
                  3: {'col_b_1': '124',
                      'col_b_2': 'EB',
                      'col_b_3': '3',
                      'col_b_4': 'aa'},
                  'sno': 3},
        'tbl_c': {1: {'col_c_1': '124',
                      'col_c_2': 'EB',
                      'col_c_3': '3',
                      'col_c_4': 'aa'},
                  'sno': 1}},
 'EB': {'name': 'dml_pkg'},
 'EE': {'name': 'dml_pkg'},
 'EK': {'name': 'dml_pkg'}}