all_tables ={'EA': {'name': 'pkg',
        'table_name': {'column_name': {'len': 'length', 'type': 'type'}},
        'tbl_a': {'col_a_1': {'len': 5, 'type': 'char'},
                  'col_a_10': {'len': 6, 'type': 'char'},
                  'col_a_2': {'len': 6, 'type': 'char'},
                  'col_a_3': {'len': 7, 'type': 'char'},
                  'col_a_4': {'len': 8, 'type': 'char'},
                  'col_a_5': {'len': 1, 'type': 'number'},
                  'col_a_6': {'len': 2, 'type': 'char'},
                  'col_a_7': {'len': 3, 'type': 'char'},
                  'col_a_8': {'len': 3, 'type': 'char'},
                  'col_a_9': {'len': 5, 'type': 'char'}},
        'tbl_b': {'col_b_1': {'len': 7, 'type': 'char'},
                  'col_b_2': {'len': 10, 'type': 'char'},
                  'col_b_3': {'len': 3, 'type': 'char'},
                  'col_b_4': {'len': 4, 'type': 'char'},
                  'col_b_5': {'len': 5, 'type': 'number'}},
        'tbl_c': {'col_c_1': {'len': 6, 'type': 'number'},
                  'col_c_2': {'len': 7, 'type': 'number'},
                  'col_c_3': {'len': 8, 'type': 'number'},
                  'col_c_4': {'len': 9, 'type': 'number'},
                  'col_c_5': {'len': 1, 'type': 'number'}},
        'tbl_e': {'col_e_1': {'len': 2, 'type': 'number'},
                  'col_e_2': {'len': 3, 'type': 'number'},
                  'col_e_3': {'len': 4, 'type': 'char'}}},
 'EB': {'name': 'pkg',
        'table_name': {'column_name': {'len': 'length', 'type': 'type'}},
        'tbl_a': {'col_a_1': {'len': 5, 'type': 'char'},
                  'col_a_10': {'len': 6, 'type': 'char'},
                  'col_a_2': {'len': 6, 'type': 'char'},
                  'col_a_3': {'len': 7, 'type': 'char'},
                  'col_a_4': {'len': 8, 'type': 'char'},
                  'col_a_5': {'len': 1, 'type': 'number'},
                  'col_a_6': {'len': 2, 'type': 'char'},
                  'col_a_7': {'len': 3, 'type': 'char'},
                  'col_a_8': {'len': 3, 'type': 'char'},
                  'col_a_9': {'len': 5, 'type': 'char'}},
        'tbl_b': {'col_b_1': {'len': 7, 'type': 'char'},
                  'col_b_2': {'len': 10, 'type': 'char'},
                  'col_b_3': {'len': 3, 'type': 'char'},
                  'col_b_4': {'len': 4, 'type': 'char'},
                  'col_b_5': {'len': 5, 'type': 'number'}},
        'tbl_c': {'col_c_1': {'len': 6, 'type': 'number'},
                  'col_c_2': {'len': 7, 'type': 'number'},
                  'col_c_3': {'len': 8, 'type': 'number'},
                  'col_c_4': {'len': 9, 'type': 'number'},
                  'col_c_5': {'len': 1, 'type': 'number'}},
        'tbl_e': {'col_e_1': {'len': 2, 'type': 'number'},
                  'col_e_2': {'len': 3, 'type': 'number'},
                  'col_e_3': {'len': 4, 'type': 'char'}}},
 'EE': {'name': 'pkg'},
 'EK': {'name': 'pkg'}}